
# 0 - Empty tiles
# 13 - Possible moves

# White                        Black
# -------------------          ------------------
# | 1 | Pawn    | P |         | 7 | Pawn    | p |
# | 2 | Rook    | R |         | 8 | Rook    | r |
# | 3 | Knight  | N |         | 9 | Knight  | n |
# | 4 | Bishop  | B |         | 10| Bishop  | b |
# | 5 | Queen   | Q |         | 11| Queen   | q |
# | 6 | King    | K |         | 12| King    | k |
# -------------------         -------------------

GAME_START:
  - [8,  9, 10, 12, 11, 10,  9,  8]
  - [7,  7,  7,  7,  7,  7,  7,  7]
  - [0,  0,  0,  0,  0,  0,  0,  0]  
  - [0,  0,  0,  0,  0,  0,  0,  0]  
  - [0,  0,  0,  0,  0,  0,  0,  0]  
  - [0,  0,  0,  0,  0,  0,  0,  0]
  - [1,  1,  1,  1,  1,  1,  1,  1]
  - [2,  3,  4,  6,  5,  4,  3,  2]

PIECE_REPRESENTATION:
  0: ' '   # Empty tiles 
  1: '♟'   # White Pawn
  2: '♜'   # White Rook
  3: '♞'   # White Knight
  4: '♝'   # White Bishop
  5: '♛'   # White Queen
  6: '♚'   # White King
  7: '♙'   # Black Pawn
  8: '♖'   # Black Rook
  9: '♘'   # Black Knight
  10: '♗'  # Black Bishop
  11: '♕'  # Black Queen
  12: '♔'  # Black King
  13: '+'  # Possible moves
